### ISSUE TITLE
Error messages about duplicate atom key

### ISSUE THREAD

**Issue by CarlBishop** [npwd-community/npwd_qb_mail#11]
For your info, I don't know what this means
![image](https://user-images.githubusercontent.com/12203647/186935009-e7c7d75f-853c-46c8-84ea-2c8bd012f022.png)

**Comment by SamShanks1** [comment]
The message is safe to ignore

**Comment by Smokiiee** [comment]
it maybe safe but i do not want it to spam the consol every time you open phone or go back to homepage from apps. 
Is there a way to remove it ?

**Comment by Smokiiee** [comment]
@SamShanks1
